#!/usr/bin/env python3
"""Generate Localizable.xcstrings (en source keys, pt-BR translations)."""
import json
from pathlib import Path

# English key (also development-language value) → pt-BR
PAIRS = [
    # Menu bar
    ("On", "Ligado"),
    ("Enter translates and sends", "Enter traduz e envia"),
    ("Hint near pointer", "Aviso perto do ponteiro"),
    ("Popup mode", "Modo popup"),
    ("Text I read →", "Texto que leio →"),
    ("Text I write →", "Texto que escrevo →"),
    ("Target language when translating read-only text (chats, panel).",
     "Idioma destino ao traduzir texto só leitura (conversas, painel)."),
    ("Target language when replacing text in editable fields.",
     "Idioma destino ao substituir texto em campos editáveis."),
    ("Configure…", "Configurar…"),
    ("Open Settings, Provider section", "Abrir Configurações, seção Provedor"),
    ("Opens the Settings window on the Provider section",
     "Abre a janela de Configurações na seção Provedor"),
    ("Shortcuts inactive. Turn on Input Monitoring.",
     "Atalhos inativos. Ative o Monitoramento de Entrada."),
    ("Fix…", "Corrigir…"),
    ("Open Settings, Permissions section", "Abrir Configurações, seção Permissões"),
    ("Opens Settings so you can grant Input Monitoring",
     "Abre Configurações para conceder Monitoramento de Entrada"),
    ("Less", "Menos"),
    ("Details", "Detalhes"),
    ("Clear", "Limpar"),
    ("View logs", "Ver logs"),
    ("Open Settings, Logs section", "Abrir Configurações, seção Logs"),
    ("Opens the logs to diagnose the failure", "Abre os logs para diagnosticar a falha"),
    ("Settings", "Configurações"),
    ("Open Settings", "Abrir Configurações"),
    ("Help", "Ajuda"),
    ("Open setup tutorial", "Abrir tutorial de configuração"),
    ("Quit", "Sair"),
    ("Panel shortcut: %@. Translate: %@.",
     "Atalho do painel: %@. Traduzir: %@."),
    ("Translate shortcut: %@. Turn on popup mode for the panel shortcut.",
     "Atalho Traduzir: %@. Ative o modo popup para o atalho do painel."),
    ("Translate %@ · Panel %@", "Traduzir %@ · Painel %@"),
    ("Translate %@ · Panel off", "Traduzir %@ · Painel desligado"),
    ("Translation engine: %@", "Motor de tradução: %@"),
    # Status
    ("Active", "Ativo"),
    ("Paused", "Pausado"),
    ("Translating…", "Traduzindo…"),
    ("Done", "Concluído"),
    ("Error", "Erro"),
    ("Status: %@", "Status: %@"),
    ("Translation complete", "Tradução concluída"),
    ("Translation failed", "Falha na tradução"),
    ("View details", "Ver detalhes"),
    ("Shows the logs for the translation failure", "Mostra os logs da falha na tradução"),
    ("Dismiss", "Dispensar"),
    ("Dismiss notice", "Dispensar aviso"),
    # Panel
    ("Close", "Fechar"),
    ("Close translation panel", "Fechar painel de tradução"),
    ("Copied", "Copiado"),
    ("Copy", "Copiar"),
    ("Copy translation", "Copiar tradução"),
    ("Copies the translated text to the clipboard",
     "Copia o texto traduzido para a área de transferência"),
    ("Replace", "Substituir"),
    ("Replace text in field", "Substituir texto no campo"),
    ("Replaces the selected text with the translation",
     "Substitui o texto selecionado pela tradução"),
    ("Translation", "Tradução"),
    ("Original text", "Texto original"),
    ("Show original", "Mostrar original"),
    ("%@, languages %@", "%@, idiomas %@"),
    ("Text I write", "Texto que escrevo"),
    ("Text I read", "Texto que leio"),
    # Settings sidebar
    ("General", "Geral"),
    ("Provider", "Provedor"),
    ("Shortcuts", "Atalhos"),
    ("Permissions", "Permissões"),
    ("Test", "Teste"),
    ("Logs", "Logs"),
    ("About", "Sobre"),
    ("Daily use", "Uso diário"),
    ("System", "Sistema"),
    ("Prism Settings", "Configurações do Prism"),
    # General settings
    ("The On, Enter, HUD, target language, and popup controls are also on the menu bar icon.",
     "Os controles Ligado, Enter, HUD, idiomas destino e modo popup também ficam no ícone da barra de menus."),
    ("The Translate shortcut replaces in place if the field is editable; for read-only text it opens the panel (Copy). Popup mode (opt-in) opens the panel for any selection.",
     "O atalho Traduzir substitui no lugar se o campo for editável; em texto só leitura abre o painel (Copiar). O modo popup (opt-in) abre o painel em qualquer seleção."),
    ("Shows “Translating…”, done, and errors next to the pointer when you use the shortcut.",
     "Mostra «Traduzindo…», concluído e erros junto ao mouse ao usar o atalho."),
    ("Translate from", "Traduzir de"),
    ("Translate to", "Traduzir para"),
    ("Detect language", "Detectar idioma"),
    ("Used for read-only text and the panel when reading conversations.",
     "Usado em texto só leitura e no painel ao ler conversas."),
    ("Used when replacing text in editable fields.",
     "Usado ao substituir texto em campos editáveis."),
    ("More options", "Mais opções"),
    ("Open Shortcuts…", "Abrir Atalhos…"),
    ("Go to Shortcuts section", "Ir para seção Atalhos"),
    ("Shows the Shortcuts section in this window", "Mostra a seção Atalhos nesta janela"),
    ("Open Provider…", "Abrir Provedor…"),
    ("Go to Provider section", "Ir para seção Provedor"),
    ("Shows the Provider section in this window", "Mostra a seção Provedor nesta janela"),
    ("Open at login", "Abrir no login"),
    # Provider
    ("Engine", "Motor"),
    ("Configuration", "Configuração"),
    ("No API key. Translation runs on this Mac with languages downloaded in macOS.",
     "Sem API key. A tradução roda no aparelho com os idiomas baixados no macOS."),
    ("Download…", "Baixar…"),
    ("Download languages in use…", "Baixar idiomas usados…"),
    ("Opens the system dialog to download source and target packs",
     "Abre o diálogo do sistema para baixar os pacotes de origem e destino"),
    ("Open Translation Languages in System Settings…",
     "Abrir Idiomas de Tradução nos Ajustes…"),
    ("Opens System Settings to the translation languages list",
     "Abre Ajustes do Sistema na lista de idiomas de tradução"),
    ("Download source and target. The button above asks macOS to download them; if nothing appears, use Settings › General › Language & Region › Translation Languages. With On-Device Mode on, translation stays offline.",
     "Baixe origem e destino. O botão acima pede o download pelo diálogo do macOS; se ele não aparecer, use Ajustes › Geral › Idioma e Região › Idiomas de Tradução. Com “Modo no dispositivo” ligado, a tradução fica offline."),
    ("DeepL API Key", "API Key DeepL"),
    ("DeepL API key (Free or Pro account). Stored in the Keychain.",
     "Chave da API DeepL (conta Free ou Pro). Guardada no Keychain."),
    ("Secret DeepL API key, stored in the Keychain",
     "Chave secreta da API DeepL, armazenada no Keychain"),
    ("Use Free API (api-free.deepl.com)", "Usar API Free (api-free.deepl.com)"),
    ("Google Cloud Translation API Key", "API Key Google Cloud Translation"),
    ("Google Cloud Translation API key. Stored in the Keychain.",
     "Chave da API Google Cloud Translation. Guardada no Keychain."),
    ("Secret Google Cloud API key, stored in the Keychain",
     "Chave secreta da API Google Cloud, armazenada no Keychain"),
    ("Base URL", "Base URL"),
    ("OpenAI-compatible endpoint, for example local LM Studio.",
     "Endpoint compatível com OpenAI, por exemplo LM Studio local."),
    ("Model", "Modelo"),
    ("API Key (optional)", "API Key (opcional)"),
    ("Optional for local servers. Stored in the Keychain.",
     "Opcional para servidores locais. Guardada no Keychain."),
    ("Optional API key, stored in the Keychain",
     "Chave de API opcional, armazenada no Keychain"),
    ("Default LM Studio: http://localhost:1234/v1",
     "LM Studio padrão: http://localhost:1234/v1"),
    ("URL", "URL"),
    ("Method", "Método"),
    ("JSON headers", "Headers JSON"),
    ("Body template", "Body template"),
    ("Response JSON path", "JSON path da resposta"),
    ("Placeholders: {{text}}, {{to}}, {{from}}", "Placeholders: {{text}}, {{to}}, {{from}}"),
    ("Checking languages…", "Verificando idiomas…"),
    ("Translation languages ready", "Idiomas de tradução prontos"),
    ("One or more languages still need downloading", "Falta baixar um ou mais idiomas"),
    ("Downloading — confirm the system dialog", "Baixando — confirme o diálogo do sistema"),
    ("Language pair not supported", "Par de idiomas não suportado"),
    ("Failed: %@", "Falha: %@"),
    ("Checking…", "Verificando…"),
    ("Ready", "Pronto"),
    ("Not downloaded", "Não baixado"),
    ("Downloading…", "Baixando…"),
    ("Not supported", "Não suportado"),
    ("Failed", "Falhou"),
    ("On this device", "No dispositivo"),
    ("Classic translation", "Tradução clássica"),
    ("Advanced", "Avançado"),
    ("AI", "IA"),
    ("Local", "Local"),
    ("Free", "Grátis"),
    ("Paid", "Pago"),
    ("Default", "Padrão"),
    ("Custom HTTP", "HTTP personalizado"),
    ("Apple on-device translation — no API key.",
     "Tradução on-device da Apple — sem API key."),
    ("Local OpenAI-compatible server (LM Studio, Ollama, etc.).",
     "Servidor local OpenAI-compatible (LM Studio, Ollama, etc.)."),
    # Shortcuts
    ("Global shortcuts", "Atalhos globais"),
    ("Translate", "Traduzir"),
    ("Translate and send", "Traduzir e enviar"),
    ("Restore defaults (⌃⌥T / ⌃⌥⏎ / ⌃⌥Y)", "Restaurar padrões (⌃⌥T / ⌃⌥⏎ / ⌃⌥Y)"),
    ("Enable popup mode", "Ativar modo popup"),
    ("Popup shortcut", "Atalho do popup"),
    ("Shows the translation in a panel. In editable fields, you can Copy or Replace.",
     "Mostra a tradução num painel. Em campos editáveis, permite Copiar ou Substituir."),
    ("Click the shortcut and press the new combination. Esc cancels. Prefer ⌃⌥ to avoid conflicts. Translate replaces in place (editable field) or opens the panel with Copy only (read-only). The popup shortcut — if on — opens the panel for any selection, with Replace when the field is editable. With “Enter translates and sends”, Enter alone also translates and sends.",
     "Clique no atalho e pressione a nova combinação. Esc cancela. Prefira ⌃⌥ para evitar conflitos. O atalho Traduzir substitui no lugar (campo editável) ou abre o painel só com Copiar (só leitura). O atalho de popup — se estiver ligado — abre o painel em qualquer seleção, com Substituir quando o campo for editável. Com “Enter traduz e envia”, Enter sozinho também traduz e envia."),
    ("Press the shortcut…", "Pressione o atalho…"),
    ("Esc cancels", "Esc cancela"),
    ("Click to record a new shortcut", "Clique para gravar um novo atalho"),
    ("This shortcut is already in use.", "Este atalho já está em uso."),
    # Permissions
    ("Required", "Necessárias"),
    ("Accessibility granted", "Acessibilidade concedida"),
    ("Accessibility required", "Acessibilidade necessária"),
    ("Read and replace text in the focused field.",
     "Ler e substituir o texto do campo focado."),
    ("Input Monitoring granted", "Monitoramento de Entrada concedido"),
    ("Input Monitoring required", "Monitoramento de Entrada necessário"),
    ("Captures global shortcuts (⌃⌥T, ⌃⌥⏎) in any app.",
     "Captura os atalhos globais (⌃⌥T, ⌃⌥⏎) em qualquer app."),
    ("Open System Settings", "Abrir Ajustes"),
    ("Opens System Settings to grant this permission",
     "Abre Ajustes do Sistema para conceder esta permissão"),
    # Test
    ("Input", "Entrada"),
    ("Text", "Texto"),
    ("Current engine", "Motor atual"),
    ("Target (outgoing)", "Destino (suas)"),
    ("Test translation", "Testar tradução"),
    ("Result", "Resultado"),
    ("Checks the engine and the “text I write” pair in this window. Does not open the panel, HUD, or fire shortcuts.",
     "Valida o motor e o par «texto que escrevo» nesta janela. Não abre o painel, o HUD nem dispara atalhos."),
    ("Run a test to validate the configured engine and language.",
     "Rode um teste para validar o motor e o idioma configurados."),
    ("A shortcut translation is still running. Wait and try again.",
     "Uma tradução por atalho ainda está em andamento. Aguarde e tente de novo."),
    ("Hello, world!", "Olá, mundo!"),
    # About
    ("Version %@ (%@)", "Versão %@ (%@)"),
    ("Prism Translate, version %@, build %@", "Prism Translate, versão %@, build %@"),
    ("The App", "O App"),
    ("Translates the focused field in any app — one shortcut, in place, no copy and paste.",
     "Traduz o texto do campo focado em qualquer app — um atalho, no lugar, sem copiar e colar."),
    ("Engines: Apple Translation on this Mac, DeepL, Google Translate, and local LM Studio. The interface lives in the menu bar — almost invisible.",
     "Motores: Apple Translation no aparelho, DeepL, Google Translate e LM Studio local. A interface fica na barra de menus — quase invisível."),
    ("The Team", "O Time"),
    ("Creator and developer", "Criador e desenvolvedor"),
    ("Solo project: from idea to design, from code to release. Crafted so translation never gets in the way of people who write all day.",
     "Projeto solo: da ideia ao design, do código ao release. Feito com cuidado artesanal para traduzir sem atrapalhar quem escreve o dia inteiro."),
    ("Location", "Localização"),
    ("Open GitHub for %@", "Abrir GitHub de %@"),
    ("History", "História"),
    ("Created", "Criado em"),
    ("August 2, 2026", "2 de agosto de 2026"),
    ("Original name", "Nome original"),
    ("Rebrand", "Rebrand"),
    ("Prism Translate — Aug 2026", "Prism Translate — ago. 2026"),
    ("It started as a simple menu-bar translator that replaces text in place. The rebrand brought a new identity, but the spirit is the same: translate without getting in the way.",
     "Nasceu como um tradutor simples de menu bar focado em substituir o texto no lugar. O rebrand trouxe uma identidade nova, mas o espírito continua o mesmo: traduzir sem atrapalhar."),
    ("What’s new in %@", "Novidades da %@"),
    ("Updates", "Atualizações"),
    ("Channel", "Canal"),
    ("Pre-release", "Pré-lançamento"),
    ("Distribution", "Distribuição"),
    ("GitHub Releases (outside the App Store)", "GitHub Releases (fora da App Store)"),
    ("Check for Updates", "Verificar atualizações"),
    ("Download %@…", "Baixar %@…"),
    ("You’re already on the latest version.", "Você já está na versão mais recente."),
    ("This build is ahead of the last published release (%@).",
     "Esta build está à frente da última publicação (%@)."),
    ("Version %@ is available.", "Versão %@ disponível."),
    ("No version has been published on GitHub yet. When one is, this button will point to the download.",
     "Ainda não há versão publicada no GitHub. Quando houver, este botão aponta para o download."),
    ("Couldn’t check: %@", "Não foi possível verificar: %@"),
    ("Support", "Suporte"),
    ("Reopen setup tutorial…", "Reabrir tutorial de configuração…"),
    ("Reopen setup tutorial", "Reabrir tutorial de configuração"),
    ("Report a problem…", "Reportar problema…"),
    ("Opens a GitHub issue with version and system filled in",
     "Abre uma issue no GitHub com versão e sistema preenchidos"),
    ("Copy app info", "Copiar informações do app"),
    ("Copies version, build, identifier, and current engine to the clipboard",
     "Copia versão, build, identificador e motor atual para a área de transferência"),
    ("Open Logs…", "Abrir Logs…"),
    ("Shows the Logs section in this window", "Mostra a seção Logs nesta janela"),
    ("Copied info", "Informações copiadas"),
    ("Legal", "Legal"),
    ("Source code is available for noncommercial use. Apple Translation, DeepL, Google Translate, and LM Studio are trademarks of their owners. Prism uses them as optional translation engines.",
     "Código-fonte disponível para uso não comercial. Apple Translation, DeepL, Google Translate e LM Studio são marcas dos respectivos donos. O Prism os usa como motores de tradução opcionais."),
    ("View license", "Ver licença"),
    ("Open the PolyForm Noncommercial license text",
     "Abrir o texto da licença PolyForm Noncommercial"),
    ("Open the PolyForm Noncommercial license page",
     "Abrir a página da licença PolyForm Noncommercial"),
    ("GitHub repository", "Repositório no GitHub"),
    ("Open repository on GitHub", "Abrir repositório no GitHub"),
    ("Releases page", "Página de releases"),
    ("Open the GitHub releases page", "Abrir página de releases no GitHub"),
    ("Channel: pre-release", "Canal: pré-lançamento"),
    ("System: %@", "Sistema: %@"),
    ("Minimum: macOS 15.0", "Mínimo: macOS 15.0"),
    ("Engine: %@", "Motor: %@"),
    # Logs
    ("Warning", "Aviso"),
    ("No entries", "Sem entradas"),
    ("Translate something or adjust the filters to see the log.",
     "Traduza algo ou ajuste os filtros para ver o log."),
    ("Level", "Nível"),
    ("Category", "Categoria"),
    ("All", "Todas"),
    ("Copy all", "Copiar tudo"),
    ("Copies the full log to the clipboard (to paste in chat, email, etc.)",
     "Copia o log completo para a área de transferência (para colar no chat, e-mail, etc.)"),
    ("Auto-scroll", "Auto-scroll"),
    ("Source", "Fonte"),
    ("Shows file and line for each entry", "Mostra arquivo e linha de cada entrada"),
    ("Search the log…", "Buscar no log…"),
    ("Copy line", "Copiar linha"),
    ("Filter this run", "Filtrar este run"),
    ("%lld of %lld on screen", "%lld de %lld na tela"),
    ("Save file…", "Salvar arquivo…"),
    ("Saves a full .log to any folder", "Salva um .log completo em qualquer pasta"),
    ("Show in Finder", "Mostrar no Finder"),
    ("Copied (%lld)", "Copiado (%lld)"),
    ("Saved: %@ (%lld lines)", "Salvo: %@ (%lld linhas)"),
    ("Save Prism log", "Salvar log do Prism"),
    # Onboarding
    ("Translate without leaving the field", "Traduza sem sair do campo"),
    ("Prism translates and replaces the focused field in any app — no extra windows, no copy and paste.",
     "O Prism traduz e substitui o texto do campo focado em qualquer app — sem janelas, sem copiar e colar."),
    ("Accessibility permission", "Permissão de Acessibilidade"),
    ("This is what lets Prism read and replace the text you type. Without it, translation cannot run.",
     "É o que permite ler e substituir o texto do campo em que você digita. Sem ela, a tradução não acontece."),
    ("Input Monitoring", "Monitoramento de Entrada"),
    ("Delivers global shortcuts even when another app is frontmost. Without it, ⌃⌥T looks like it “does nothing”.",
     "Entrega os atalhos globais ao app mesmo com outro app em primeiro plano. Sem ele, ⌃⌥T parece “não fazer nada”."),
    ("Language and translation", "Idioma e tradução"),
    ("Choose the target language. With Apple Translation, packs download now and translation runs on this Mac.",
     "Escolha o idioma destino. Com Apple Translation, os pacotes são baixados agora e a tradução roda no aparelho."),
    ("Shortcuts in practice", "Atalhos na prática"),
    ("These are your current shortcuts. You can change them in Settings → Shortcuts.",
     "Estes são os seus atalhos atuais. Dá para trocá-los em Configurações → Atalhos."),
    ("You’re all set", "Tudo pronto"),
    ("Check the list — the prism icon stays in the menu bar to turn Prism on or off, change language, and open Settings.",
     "Confira o checklist — o ícone do prisma fica na barra de menus para ligar/desligar, trocar idioma e abrir as Configurações."),
    ("Setup", "Configuração"),
    ("Step %lld of %lld", "Etapa %lld de %lld"),
    ("Step %lld of %lld: %@", "Etapa %lld de %lld: %@"),
    ("Translates and replaces in place", "Traduz e substitui no lugar"),
    ("Translates, replaces, and sends", "Traduz, substitui e envia"),
    ("You can continue and grant this later — translation only works with this permission.",
     "Você pode continuar e conceder depois — a tradução só funciona com esta permissão."),
    ("Without it, global shortcuts stay inactive — the menu bar warns you when that happens.",
     "Sem ela os atalhos globais ficam inativos — o menu bar avisa quando isso acontecer."),
    ("Target language (your messages)", "Idioma destino (suas mensagens)"),
    ("Open Settings → Provider", "Abrir Configurações → Provedor"),
    ("Prefer DeepL, Google, or LM Studio? Configure the engine in Settings → Provider.",
     "Prefere DeepL, Google ou LM Studio? Configure o motor em Configurações → Provedor."),
    ("Selects the field text, translates, and replaces",
     "Seleciona o texto do campo, traduz e substitui"),
    ("Does the same and sends (Enter)", "Faz o mesmo e envia (Enter)"),
    ("Shows the result in a panel (popup mode)",
     "Mostra o resultado num painel (modo popup)"),
    ("Only if “Enter translates and sends” is on in the menu",
     "Só se “Enter traduz e envia” estiver ligado no menu"),
    ("Open Settings → Shortcuts", "Abrir Configurações → Atalhos"),
    ("Open Settings, Shortcuts section", "Abrir Configurações, seção Atalhos"),
    ("Opens the Settings window on the Shortcuts section",
     "Abre a janela de Configurações na seção Atalhos"),
    ("Skip", "Pular"),
    ("Jumps to the final checklist without finishing the tutorial.",
     "Pula para o checklist final sem concluir o tutorial."),
    ("Shows the checklist with pending items", "Mostra o checklist com itens pendentes"),
    ("Back", "Voltar"),
    ("Finish", "Concluir"),
    ("Get started", "Começar"),
    ("Continue", "Continuar"),
    ("Open System Settings…", "Abrir Ajustes do Sistema…"),
    ("Accessibility", "Acessibilidade"),
    ("Translation languages (%@)", "Idiomas de tradução (%@)"),
    ("Prism icon in the menu bar", "Ícone do prisma na barra de menus"),
    ("Open Settings → Permissions", "Abrir Configurações → Permissões"),
    ("Opens the Settings window on the Permissions section",
     "Abre a janela de Configurações na seção Permissões"),
    ("Orange items are still pending — you can fix them now or later from the menu.",
     "Itens em laranja ficam pendentes — você pode corrigir agora ou depois pelo menu."),
    ("%@: %@", "%@: %@"),
    ("ready", "pronto"),
    ("pending", "pendente"),
    ("Try again", "Tentar de novo"),
    ("Download languages…", "Baixar idiomas…"),
    ("Languages ready (target: %@)", "Idiomas prontos (destino: %@)"),
    ("Download needed (target: %@)", "Download necessário (destino: %@)"),
    ("Downloading languages — confirm the system dialog",
     "Baixando idiomas — confirme o diálogo do sistema"),
    ("Language pair not supported — change the target or the provider",
     "Par de idiomas não suportado — mude o destino ou o provedor"),
    ("Download not completed", "Download não concluído"),
    ("Welcome to Prism", "Bem-vindo ao Prism"),
    # Errors / providers
    ("Provider unavailable: %@", "Provedor indisponível: %@"),
    ("Empty response from provider", "Resposta vazia do provedor"),
    ("Apple Translation: %@", "Apple Translation: %@"),
    ("API balance or quota exhausted. Top up credits with the provider or switch engines in Settings.",
     "Saldo ou cota da API esgotados. Recarregue créditos no provedor ou troque o motor nas Configurações."),
    ("Invalid API key or missing permission. Check the key in Settings.",
     "API key inválida ou sem permissão. Verifique a chave nas Configurações."),
    ("Request limit reached. Wait a moment and try again.",
     "Limite de requisições atingido. Aguarde um momento e tente de novo."),
    ("API model unavailable or discontinued. Update the model in Settings.",
     "Modelo da API indisponível ou descontinuado. Atualize o modelo nas Configurações."),
    ("The provider is unavailable (HTTP %lld). Try again in a moment.",
     "O provedor está indisponível (HTTP %lld). Tente novamente em instantes."),
    ("Provider error (HTTP %lld): %@", "Erro do provedor (HTTP %lld): %@"),
    ("Provider error (HTTP %lld).", "Erro do provedor (HTTP %lld)."),
    ("Set the DeepL API key in Settings", "Configure a API key do DeepL nas Configurações"),
    ("Invalid DeepL URL", "URL DeepL inválida"),
    ("Set the Google API key in Settings", "Configure a API key do Google nas Configurações"),
    ("Invalid Google URL", "URL Google inválida"),
    ("Set the Custom HTTP URL", "Configure a URL do Custom HTTP"),
    ("Set base URL and model for %@", "Configure base URL e modelo para %@"),
    ("Set the API key for %@ in Settings", "Configure a API key de %@ nas Configurações"),
    ("Invalid base URL", "Base URL inválida"),
    ("Previous translation canceled", "Tradução anterior cancelada"),
    ("Set a source language or download packs in Settings › General › Language & Region › Translation Languages",
     "Defina o idioma de origem ou baixe os pacotes em Ajustes › Geral › Idioma e Região › Idiomas de Tradução"),
    ("Language pair not supported — choose another language or provider",
     "Par de idiomas não suportado — escolha outro idioma ou provedor"),
    ("Timed out — with On-Device Mode on, download languages in Settings › General › Language & Region › Translation Languages",
     "Tempo esgotado — com “Modo no dispositivo” ligado, baixe os idiomas em Ajustes › Geral › Idioma e Região › Idiomas de Tradução"),
    ("Accessibility permission required — open System Settings › Privacy › Accessibility",
     "Permissão de Acessibilidade necessária — abra Ajustes do Sistema › Privacidade › Acessibilidade"),
    ("No focused text field", "Nenhum campo de texto focado"),
    ("Select the text to translate", "Selecione o texto para traduzir"),
    ("Couldn’t read the field text", "Não foi possível ler o texto do campo"),
    ("Couldn’t replace the text", "Não foi possível substituir o texto"),
    ("Failed to read the field (Accessibility and clipboard fallback both failed)",
     "Falha ao ler o campo (Acessibilidade e fallback de clipboard falharam)"),
    ("Failed to replace the text (Accessibility and clipboard fallback both failed)",
     "Falha ao substituir o texto (Acessibilidade e fallback de clipboard falharam)"),
    ("automatic detection", "detecção automática"),
    ("Prism is off — turn it on in Settings",
     "Prism está desligado — ligue nas Configurações"),
    ("Previous translation still running — wait",
     "Tradução anterior ainda em andamento — aguarde"),
    ("No text in the focused field", "Nenhum texto no campo focado"),
    ("Shortcut %@", "Atalho %@"),
    ("With On-Device Mode on, download source and target languages in System Settings › General › Language & Region › Translation Languages — or turn the mode off to translate online.",
     "Com “Modo no dispositivo” ligado, baixe os idiomas (origem e destino) em Ajustes do Sistema › Geral › Idioma e Região › Idiomas de Tradução — ou desligue o modo para traduzir online."),
]

def main():
    strings = {}
    for en, pt in PAIRS:
        strings[en] = {
            "localizations": {
                "pt-BR": {
                    "stringUnit": {
                        "state": "translated",
                        "value": pt,
                    }
                }
            }
        }
    catalog = {
        "sourceLanguage": "en",
        "strings": strings,
        "version": "1.0",
    }
    out = Path(__file__).resolve().parents[1] / "Prism" / "Localizable.xcstrings"
    out.write_text(json.dumps(catalog, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(strings)} keys to {out}")

if __name__ == "__main__":
    main()
